[workspace]
authors = ["Luigi Freda <luigifreda@gmail.com>"]
channels = ["conda-forge"]
name = "pyslam-pixi"
platforms = ["linux-64"]
version = "2.10.0"
preview = ["pixi-build"]  

[dependencies]
python = "==3.11.9"
pip = ">=25.1.1,<26"
absl-py = "*"
astor = "*"
cycler = "*"
decorator = "*"
gast = "*"
google-pasta = "*"
grpcio = "*"
h5py = "*"
imageio = "*"
keras = "*"
kiwisolver = "*"
markdown = "*"
matplotlib = "*"
networkx = "*"
ordered-set = "*"
pillow = "*"
psutil = "*"
pybind11 = "*"
eigen = "*"
pygame = "*"
compilers = "*"
cmake = "<4"
ninja = "*"
pyopengl = "*"
pyopenssl = "*"
pyparsing = "*"
python-dateutil = "*"
pyyaml = "*"
scipy = ">=1.15.2,<2"
scikit-image = ">=0.25.2,<0.26"
seaborn = ">=0.13.2,<0.14"
six = "*"
sklearn-pandas = "*"
termcolor = "*"
tqdm = "*"
werkzeug = "*"
wrapt = "*"
yacs = "*"
wget = "*"
doxygen = "*"
glew = "*"
pkg-config = "*"
suitesparse = "*"
zlib = "*"
bzip2 = "*"
rsync = "*"
readline = "*"
libboost-devel = "*"
flann = "*"
catch2 = "*"
gdown = "*"
x265 = "*"
libheif = "*"
gtk2 = "*"
hdf5 = "*"
tmux = "*"
nano = "*"
wheel = "*"
pytorch-gpu = "*"
torchvision = "*"
ujson = ">=5.10.0,<6"
einops = ">=0.8.1,<0.9"
pyflann = "*"
faiss = "*"
trimesh = "*"
jax = "*"
munch = "*"
wandb = "*"
plyfile = "*"
torchmetrics = "*"
pyglm = "*"
lpips = "*"
rich = "*"
ruff = "*"
gradio = "*"
pytorch3d = "*"
libgl-devel = "*"
libopengl-devel = "*"
libegl-devel = "*"
libglx-devel = "*"
cython = "0.29.*"
cuda-compiler = "12.1.*"
metis = "*"
rerun-sdk = "*"
rattler-build = "*"
fast-pytorch-kmeans = "*"
timm = "*"
pillow-heif = "*"
evo = "*"
quaternion = "*"
open3d = "*"
gtsam = "*"
tbb = ">=2021.13.0,<2022"
tbb-devel = ">=2021.13.0,<2022"
pyqtgraph = "*"
viser="*"
vtk = ">=9.3.1,<10"
ffmpeg = ">=7.1.1,<8"
jinja2 = ">=3.1.6,<4"
glib = "*"
gobject-introspection = "*"
spdlog = "*"
console_bridge = "*"
tinyxml2 = "*"
configargparse = "*"
python-devtools = ">=0.12.2,<0.13"

[tool.pixi.pip-dependencies]
numba = "*"
onnxruntime = "*"
imgviz = "==1.2.6"
glfw = "*"
roma = "*"
pyqt5 = "*"
kornia = "==0.7.3"
kornia_moons = "==0.2.9"
#transformers = "==4.38.2" 
#f3rm = "*"                # conflict 
#timm = "==1.0.15"         # conflict 
#tensorflow = "==2.13"     # conflict 
#tensorflow-hub = "*"      # conflict 
#protobuf = ">=3.20"       # conflict 

[system-requirements]
cuda = "12.1"
